# Generated by Django 4.0.6 on 2022-07-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Presidente', 'Presidente'), ('Vice-presidente', 'Vice-Presidente'), ('Secretário', 'Secretário'), ('Participante', 'Participante')], default='Participante', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('assunto', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datai', models.DateTimeField()),
                ('duracao', models.IntegerField()),
                ('assunto', models.CharField(max_length=150)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.participante')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.reuniao')),
            ],
        ),
        migrations.CreateModel(
            name='Presencas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.participante')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.reuniao')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.utilizador'),
        ),
        migrations.AddField(
            model_name='participante',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.reuniao'),
        ),
        migrations.CreateModel(
            name='Intervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datai', models.DateTimeField()),
                ('dataf', models.DateTimeField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.participante')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.reuniao')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(max_length=255, upload_to='media')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingApp.reuniao')),
            ],
        ),
    ]
